CREATE TABLE IF NOT EXISTS demo_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS demo_environment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    deployment_branch VARCHAR(160),
    CONSTRAINT fk_demo_environment_project FOREIGN KEY (project_id) REFERENCES demo_project(id) ON DELETE CASCADE,
    CONSTRAINT uk_demo_environment_project_code UNIQUE (project_id, code)
);

CREATE TABLE IF NOT EXISTS demo_repository (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    environment_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    repository_url VARCHAR(1000) NOT NULL,
    base_branch VARCHAR(160) NOT NULL,
    primary_repo BOOLEAN NOT NULL,
    CONSTRAINT fk_demo_repository_project FOREIGN KEY (project_id) REFERENCES demo_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_demo_repository_environment FOREIGN KEY (environment_id) REFERENCES demo_environment(id) ON DELETE CASCADE,
    CONSTRAINT uk_demo_repository_environment_code UNIQUE (environment_id, code)
);

CREATE TABLE IF NOT EXISTS demo_database (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    environment_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    username VARCHAR(240),
    password VARCHAR(500),
    schema_hint VARCHAR(1000),
    CONSTRAINT fk_demo_database_project FOREIGN KEY (project_id) REFERENCES demo_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_demo_database_environment FOREIGN KEY (environment_id) REFERENCES demo_environment(id) ON DELETE CASCADE,
    CONSTRAINT uk_demo_database_environment_code UNIQUE (environment_id, code)
);

CREATE TABLE IF NOT EXISTS demo_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    related_project_id BIGINT NOT NULL,
    direction VARCHAR(40) NOT NULL,
    relation_type VARCHAR(80) NOT NULL,
    name VARCHAR(160),
    description VARCHAR(1000),
    CONSTRAINT fk_demo_relation_project FOREIGN KEY (project_id) REFERENCES demo_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_demo_relation_related FOREIGN KEY (related_project_id) REFERENCES demo_project(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS demo_markdown_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(80) NOT NULL,
    title VARCHAR(240) NOT NULL,
    path VARCHAR(500) NOT NULL,
    category VARCHAR(120),
    content CLOB NOT NULL,
    revision INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_demo_document_project_path UNIQUE (project_code, path)
);

CREATE TABLE IF NOT EXISTS demo_markdown_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    revision INT NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_demo_version_document FOREIGN KEY (document_id) REFERENCES demo_markdown_document(id) ON DELETE CASCADE,
    CONSTRAINT uk_demo_version_revision UNIQUE (document_id, revision)
);

CREATE TABLE IF NOT EXISTS demo_log_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    environment_code VARCHAR(80) NOT NULL,
    service_name VARCHAR(160) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    level VARCHAR(20) NOT NULL,
    trace_id VARCHAR(160),
    content CLOB NOT NULL,
    CONSTRAINT fk_demo_log_project FOREIGN KEY (project_id) REFERENCES demo_project(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_demo_document_project ON demo_markdown_document(project_code);
CREATE INDEX IF NOT EXISTS idx_demo_repository_environment ON demo_repository(environment_id);
CREATE INDEX IF NOT EXISTS idx_demo_database_environment ON demo_database(environment_id);
CREATE INDEX IF NOT EXISTS idx_demo_log_resource ON demo_log_entry(project_id, environment_code, service_name, occurred_at);
CREATE INDEX IF NOT EXISTS idx_demo_log_trace ON demo_log_entry(trace_id);
