create table if not exists workbench_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    display_name varchar(80) not null,
    avatar_url varchar(500),
    password_hash varchar(200) not null,
    monthly_token_limit bigint,
    daily_token_limit bigint,
    weekly_token_limit bigint,
    role enum ('ADMIN', 'USER') not null,
    enabled boolean not null,
    last_login_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table if not exists agent_capability (
    code varchar(80) primary key,
    enabled boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table if not exists agent_scenario (
    code varchar(80) primary key,
    enabled boolean not null,
    user_visible boolean default true not null,
    sort_order integer not null,
    capabilities json not null,
    capability_commands json not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table if not exists analysis_premise (
    id bigint generated by default as identity primary key,
    code varchar(80) unique,
    name varchar(120) not null,
    description varchar(500),
    prompt_text clob,
    context_values json,
    scenario_context_values json,
    enabled boolean not null,
    global_visible boolean not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table if not exists analysis_premise_visible_scenario (
    premise_id bigint not null,
    scenario_code varchar(80) not null,
    primary key (premise_id, scenario_code),
    constraint fk_premise_visible_scenario_premise
        foreign key (premise_id) references analysis_premise(id)
);

create table if not exists analysis_premise_user (
    premise_id bigint not null,
    user_id bigint not null,
    primary key (premise_id, user_id),
    constraint fk_premise_user_premise
        foreign key (premise_id) references analysis_premise(id)
);

create table if not exists capability_config (
    id bigint generated by default as identity primary key,
    capability_code varchar(80) not null,
    name varchar(100) not null,
    description varchar(500),
    config json,
    enabled boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table if not exists model_provider (
    id varchar(100) primary key,
    owner_user_id bigint,
    provider_type varchar(40) not null,
    name varchar(120) not null,
    base_url varchar(1000) not null,
    api_key varchar(2000) not null,
    instruction_prompt clob,
    max_concurrency integer,
    enabled boolean not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_model_provider_owner
        foreign key (owner_user_id) references workbench_user(id)
);

create table if not exists model_profile (
    id varchar(100) primary key,
    owner_user_id bigint,
    provider_id varchar(100) not null,
    name varchar(120) not null,
    description varchar(500),
    model varchar(160) not null,
    protocol varchar(30) not null check (protocol in ('RESPONSES', 'CHAT_COMPLETIONS')),
    context_window_tokens integer not null,
    reasoning_effort varchar(50),
    instruction_prompt clob,
    max_concurrency integer,
    enabled boolean not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_model_profile_owner
        foreign key (owner_user_id) references workbench_user(id),
    constraint fk_model_profile_provider
        foreign key (provider_id) references model_provider(id)
);

create table if not exists model_pricing_plan (
    id varchar(100) primary key,
    provider_id varchar(100) not null,
    model_profile_id varchar(100),
    name varchar(120) not null,
    pricing json not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_model_pricing_target unique (provider_id, model_profile_id),
    constraint fk_model_pricing_provider
        foreign key (provider_id) references model_provider(id),
    constraint fk_model_pricing_model
        foreign key (model_profile_id) references model_profile(id)
);

create table if not exists runtime_config (
    id bigint primary key,
    max_task_concurrency integer,
    task_execution_timeout_minutes integer,
    global_daily_token_limit bigint,
    global_weekly_token_limit bigint,
    global_monthly_token_limit bigint,
    global_boundary_prompt clob,
    updated_at timestamp(6) not null
);

create table if not exists mcp_server (
    id varchar(36) primary key,
    code varchar(80) not null,
    name varchar(120) not null,
    instructions clob,
    transport enum ('STDIO', 'STREAMABLE_HTTP') not null,
    command varchar(1000),
    arguments json,
    url varchar(2000),
    environment json,
    headers json,
    tool_presentations json,
    enabled boolean not null,
    builtin boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_mcp_server_code unique (code)
);

create table if not exists mcp_server_runtime (
    mcp_server_id varchar(36) not null,
    runtime_code varchar(80) not null,
    primary key (mcp_server_id, runtime_code),
    constraint fk_mcp_server_runtime_server
        foreign key (mcp_server_id) references mcp_server(id)
);

create table if not exists mcp_server_activation_feature (
    mcp_server_id varchar(36) not null,
    feature_code varchar(120) not null,
    primary key (mcp_server_id, feature_code),
    constraint fk_mcp_server_feature_server
        foreign key (mcp_server_id) references mcp_server(id)
);

create table if not exists mcp_server_tool (
    mcp_server_id varchar(36) not null,
    tool_name varchar(160) not null,
    primary key (mcp_server_id, tool_name),
    constraint fk_mcp_server_tool_server
        foreign key (mcp_server_id) references mcp_server(id)
);

create table if not exists agent_task (
    id bigint generated by default as identity primary key,
    scenario_code varchar(80),
    scenario_name varchar(100),
    scenario_icon varchar(50),
    scenario_color varchar(20),
    result_format varchar(50),
    result_renderer varchar(50),
    queue_priority integer,
    premise_id bigint,
    premise_snapshot_name varchar(120),
    premise_snapshot_description varchar(500),
    premise_snapshot_context_values json,
    premise_snapshot_prompt_text clob,
    owner_user_id bigint,
    scenario varchar(50) not null,
    runtime_code varchar(50) not null,
    model_profile_id varchar(100),
    model_provider_id varchar(100),
    model_provider_name varchar(120),
    model_name varchar(120),
    model_identifier varchar(160),
    model_protocol varchar(30) check (model_protocol in ('RESPONSES', 'CHAT_COMPLETIONS')),
    model_context_window_tokens integer,
    model_reasoning_effort varchar(50),
    model_instruction_prompt clob,
    model_pricing json,
    model_image_input_supported boolean,
    status varchar(30) not null check (
        status in ('PENDING', 'RUNNING', 'WAITING_USER', 'SUCCESS', 'FAILED', 'CANCELED')
    ),
    title varchar(500) not null,
    user_input clob not null,
    input_values json,
    attachments json,
    enabled_capability_codes json,
    enabled_capability_commands json,
    prompt clob,
    runtime_instructions clob,
    runtime_user_message clob,
    presentations json,
    final_response_instructions clob,
    stdout_text varchar(2000),
    stderr_text varchar(2000),
    result_text varchar(2000),
    result_data json,
    exit_code integer,
    source_task_id bigint,
    conversation_root_task_id bigint,
    round_no integer,
    runtime_session_id varchar(100),
    runtime_session_path varchar(1000),
    request_count bigint,
    input_tokens bigint,
    cached_input_tokens bigint,
    cache_creation_input_tokens bigint,
    output_tokens bigint,
    reasoning_output_tokens bigint,
    total_tokens bigint,
    resource_memory_search_count bigint,
    resource_memory_hit_count bigint,
    resource_memory_candidate_count bigint,
    resource_memory_save_count bigint,
    resource_memory_created_count bigint,
    resource_memory_refreshed_count bigint,
    resource_memory_expired_count bigint,
    resource_memory_invalidated_count bigint,
    execution_first_feedback_ms bigint,
    execution_command_duration_ms bigint,
    execution_compaction_count bigint,
    execution_duplicate_capability_call_count bigint,
    started_at timestamp(6),
    engine_completed_at timestamp(6),
    ended_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_agent_task_premise
        foreign key (premise_id) references analysis_premise(id),
    constraint fk_agent_task_owner
        foreign key (owner_user_id) references workbench_user(id)
);

create table if not exists task_event (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    type varchar(50) not null,
    status varchar(30) not null check (status in ('RUNNING', 'SUCCESS', 'FAILED', 'INFO')),
    title varchar(500) not null,
    detail varchar(5000),
    payload json,
    created_at timestamp(6) not null,
    constraint fk_task_event_task foreign key (task_id) references agent_task(id)
);

create table if not exists task_interaction (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    input_type varchar(40) not null check (
        input_type in (
            'TEXT', 'TEXTAREA', 'YES_NO', 'DATE', 'DATETIME', 'SELECT',
            'SINGLE_CHOICE', 'MULTI_CHOICE', 'CONFIRM', 'FORM'
        )
    ),
    status varchar(40) not null check (
        status in ('PENDING', 'ANSWERED', 'SKIPPED', 'UNKNOWN', 'CANCELED', 'EXPIRED')
    ),
    question clob not null,
    content clob,
    context_key varchar(80),
    required boolean not null,
    options json,
    placeholder varchar(500),
    default_value varchar(1000),
    fields json,
    actions json,
    answer_action varchar(30) check (answer_action in ('SUBMIT', 'SKIP', 'UNKNOWN', 'CANCEL')),
    answer_action_key varchar(80),
    answer_text clob,
    answer_values json,
    selected_values json,
    answer_hint varchar(1000),
    answered_at timestamp(6),
    created_at timestamp(6) not null,
    constraint fk_task_interaction_task foreign key (task_id) references agent_task(id)
);

create table if not exists task_runtime_context_value (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    context_key varchar(120) not null,
    context_value clob,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_task_runtime_context_value unique (task_id, context_key),
    constraint fk_task_runtime_context_task foreign key (task_id) references agent_task(id)
);

create table if not exists task_share (
    id bigint generated by default as identity primary key,
    share_code varchar(40) not null unique,
    task_id bigint not null,
    created_by_user_id bigint,
    password_hash varchar(500) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_task_share_task foreign key (task_id) references agent_task(id),
    constraint fk_task_share_creator foreign key (created_by_user_id) references workbench_user(id)
);

create table if not exists task_share_round (
    share_id bigint not null,
    task_id bigint not null,
    primary key (share_id, task_id),
    constraint fk_task_share_round_share foreign key (share_id) references task_share(id),
    constraint fk_task_share_round_task foreign key (task_id) references agent_task(id)
);

create table if not exists resource_catalog_item (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    provider_code varchar(100) not null,
    provider_scope varchar(120) not null,
    source_config_id bigint,
    resource_ref varchar(300) not null,
    resource_kind varchar(100) not null,
    name varchar(300) not null,
    description varchar(2000),
    aliases json,
    labels json,
    relations json,
    search_text varchar(5000),
    revision varchar(200),
    source_task_id bigint,
    observed_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_resource_catalog_item unique (
        owner_user_id, provider_code, provider_scope, resource_ref
    )
);

create index if not exists idx_agent_scenario_sort
    on agent_scenario(enabled, sort_order);
create index if not exists idx_capability_config_capability
    on capability_config(capability_code);
create index if not exists idx_agent_task_scenario_code
    on agent_task(scenario_code);
create index if not exists idx_task_share_task_id
    on task_share(task_id);
create index if not exists idx_task_share_round_task_id
    on task_share_round(task_id);
create index if not exists idx_resource_catalog_provider_expiry
    on resource_catalog_item(owner_user_id, provider_code, expires_at);
create index if not exists idx_model_provider_owner_sort
    on model_provider(owner_user_id, sort_order);
create index if not exists idx_model_profile_owner_sort
    on model_profile(owner_user_id, sort_order);
create index if not exists idx_model_profile_provider
    on model_profile(provider_id);
create index if not exists idx_model_pricing_provider
    on model_pricing_plan(provider_id, sort_order);
